### ISSUE TITLE
Ignore some characters or at least treat them

### ISSUE THREAD

**Issue by adiron** [kav5/nqd#1]
So I tried it out. So far good stuff. I will however add one thing that bothers me.

Some characters do not have alternatives. For example a space has no alternatives: yet it shows up with the [affordance](https://en.wikipedia.org/wiki/Affordance) of changeability.

![nequd](https://cloud.githubusercontent.com/assets/117650/21740271/5dfe0ad8-d4bd-11e6-9959-36774e491b56.gif)

I see two options. It's either one, or both:

1. Add an "ignore characters". A set of characters that simply are to have no translations.
2. Add translations for the space character! There are some characters for which it can be useful: non-breaking space (0xA0), en-space (0x2002), em-space (0x2003) etc.

I am going to also work on a design solution to make this situation a little less obnoxious. I may or may not implement it, time being an issue, but I will take a few minutes of my time to show you what I mean.

**Comment by dvorakroth** [comment]
Programmatically, what happens is:
1. Every niqqud has a set of allowed letters - usually alef-tav with no finals
2. When a character is selected, only the niqqud that allows that character is shown
3. Thus, in the case of the space character, Latin letters, and mem/nun/tzadi sofiot, there is no applicable niqqud and the niqqud-keyboard is hidden

An solution, perhaps, would be to disallow clicking on and remove the hover styling from a character that has no applicable niqqud, or to replace the niqqud-keyboard with some indication that no niqqud is applicable. (Text? Cobwebs? Sad smiley? Greyed-out niqqud?)

While selecting different kinds of spaces is nice for programmers, I think it would be too confusing for "simple" users, so that's a no.

**Comment by dvorakroth** [comment]
![img_1182](https://cloud.githubusercontent.com/assets/4295016/21743954/cf900cec-d50c-11e6-94c9-519ce10103cd.JPG)
